# Basic dependabot.yml file with
# minimum configuration for the npm package manager

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/www"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
      
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/mairie"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
      
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/gouv"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
